@HostAddress = http://localhost:5174
@TOKEN = 

### Para Registrar un usuario nuevo
POST {{HostAddress}}/api/Auth/register
Content-Type: application/json

{
  "fullName": "Isaac Moncada",
  "email": "isaac@gmail.com",
  "password": "1234"
}

### Para hacer Login para que luego nos de el Token
### El token que nos de solo se coloca en @TOKEN

POST {{HostAddress}}/api/Auth/login
Content-Type: application/json

{
  "email": "isaac@gmail.com",
  "password": "1234"
}
